ICode.Web/Controllers/ProblemController.cs
using CodeStudy.Models;
using ICode.Models.Comment;
using ICode.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.DTO;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ICode.Web.Controllers
{
    public class ProblemController : Controller
    {
        private readonly IProblemService _problemService;
        private readonly ITagService _tagService;
        private readonly ISubmissionService _submissionService;
        private readonly ICommentService _commentService;

        public ProblemController(IProblemService problemService, ITagService tagService, ISubmissionService submissionService, ICommentService commentService)
        {
            _problemService = problemService;
            _tagService = tagService;
            _submissionService = submissionService;
            _commentService = commentService;
        }

        public async Task<IActionResult> Index(string id)
        {
            ProblemDTO problem = await _problemService.GetById(id);

            if (problem == null)
                return RedirectToAction("Index", "Home");

            List<CommentDetail> comments = await _commentService.GetCommentsOfProblem(id);
            ViewBag.comments = comments;

            return View(problem);
        }

        public async Task<IActionResult> Search(string tag = "", string sort = "", string keyword = "", string orderBy = "asc", string level = "", int page = 1)
        {
            PagingList<ProblemDTO> problems = await _problemService.GetPage(page, 12, keyword, tag, null, level, sort, orderBy);
            List<TagDTO> tags = await _tagService.GetAll();

            ViewBag.tags = tags;
            ViewBag.problems = problems;

            ViewData["tag"] = tag;
            ViewData["level"] = level;
            ViewData["sort"] = sort;
            ViewData["keyword"] = keyword;
            ViewData["page"] = page;
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Submissions(string id, int page = 1, bool your = false, string keyword = "", string language = "", bool? status = null, DateTime? date = null, string sort = "", string orderBy = "")
        {
            ProblemDTO problem = await _problemService.GetById(id);
            if (problem == null)
            {
                return View();
            }
            else
            {
                PagingList<SubmissionDTO> submissions;

                if (your)
                {
                   submissions = await _submissionService.GetPageSubmissionsOfProblem(id, page, 10, User.FindFirstValue(ClaimTypes.NameIdentifier), language, status, date, sort, orderBy);
                }
                else
                {
                    submissions = await _submissionService.GetPageSubmissionsOfProblem(id, page, 10, keyword, language, status, date, sort, orderBy);
                }

                ViewBag.submissions = submissions;

                ViewData["page"] = page;
                ViewData["keyword"] = keyword;
                ViewData["language"] = language;
                ViewData["status"] = status;
                ViewData["your"] = your;
                ViewData["date"] = date;
                ViewData["sort"] = sort;
                return View(problem);
            }
        }
    }
}

ICode.Web/Controllers/ProfileController.cs
using CodeStudy.Models;
using ICode.Models;
using ICode.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ICode.Web.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IUserService _userService;
        public ProfileController(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            UserDetail me = await _userService.GetProfile();
            if (me == null)
            {
                throw new Exception();
            }
            List<ProblemDTO> problemsSolved = await _userService.GetProblemSolvedByUser();

            ViewBag.problemsSolved = problemsSolved;
            return View(me);
        }
    }
}

ICode.Web/Controllers/SubmissionController.cs
using CodeStudy.Models;
using ICode.Web.Models.DTO;
using ICode.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.DTO;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ICode.Web.Controllers
{
    public class SubmissionController : Controller
    {
        private readonly ISubmissionService _submissionService;
        public SubmissionController(ISubmissionService submissionService)
        {
            _submissionService = submissionService;
        }

        [Authorize]
        public async Task<IActionResult> List(int page = 1, string keyword = "", bool your = false, string language = "", bool? status = null, DateTime? date = null, string sort = "", string orderBy = "")
        {
            PagingList<SubmissionDTO> submissions;

            if (your)
            {
                submissions = await _submissionService.GetPageSubmissionsOfUser(User.FindFirstValue(ClaimTypes.NameIdentifier), page, 10, keyword, language, status, date, sort, orderBy);
            }
            else
            {
                submissions = await _submissionService.GetPage(page, 10, keyword, language, status, date, sort, orderBy);
            }    

            ViewBag.submissions = submissions;

            ViewData["page"] = page;
            ViewData["keyword"] = keyword;
            ViewData["language"] = language;
            ViewData["status"] = status;
            ViewData["your"] = your;
            ViewData["date"] = date;
            ViewData["sort"] = sort;
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Submit(string id, SubmissionInput submission)
        {
            SubmissionResult result = await _submissionService.Submit(id, submission);
            return RedirectToAction("Detail", new { id = result.ID });
        }

        [Authorize]        
        public async Task<IActionResult> Detail(string id)
        {
            ServiceResponse<SubmissionResponse> result = await _submissionService.GetById(id);
            if (result.State)
            {
                List<SubmissionDTO> userSubmissions = await _submissionService.GetSubmissionOfProblem(result.Data.Submission.Problem.ID, User.FindFirstValue(ClaimTypes.NameIdentifier));

                ViewBag.userSubmissions = userSubmissions;
                return View(result.Data);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

ICode.Web/Views/Shared/_Footer.cshtml
<footer class="text-center mt-auto">
    <div class="container text-muted py-4 py-lg-5">
        <ul class="list-inline">
            <li class="list-inline-item me-4"><a class="link-secondary" href="#">Web design</a></li>
            <li class="list-inline-item me-4"><a class="link-secondary" href="#">Development</a></li>
            <li class="list-inline-item"><a class="link-secondary" href="#">Hosting</a></li>
        </ul>
        <ul class="list-inline">
            <li class="list-inline-item me-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                     fill="currentColor" viewBox="0 0 16 16" class="bi bi-facebook">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z">
                    </path>
                </svg>
            </li>
            <li class="list-inline-item me-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                     fill="currentColor" viewBox="0 0 16 16" class="bi bi-twitter">
                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z">
                    </path>
                </svg>
            </li>
            <li class="list-inline-item">
                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em"
                     fill="currentColor" viewBox="0 0 16 16" class="bi bi-instagram">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z">
                    </path>
                </svg>
            </li>
        </ul>
        <p class="mb-0">Copyright © 2022 Brand</p>
    </div>
</footer>

ICode.Web/Views/Shared/_Header.cshtml
<nav class="navbar navbar-light navbar-expand-md py-3">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" asp-action="Index" asp-controller="Home">
            <span class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16"
                     class="bi bi-bezier">
                    <path fill-rule="evenodd"
                          d="M0 10.5A1.5 1.5 0 0 1 1.5 9h1A1.5 1.5 0 0 1 4 10.5v1A1.5 1.5 0 0 1 2.5 13h-1A1.5 1.5 0 0 1 0 11.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm10.5.5A1.5 1.5 0 0 1 13.5 9h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM6 4.5A1.5 1.5 0 0 1 7.5 3h1A1.5 1.5 0 0 1 10 4.5v1A1.5 1.5 0 0 1 8.5 7h-1A1.5 1.5 0 0 1 6 5.5v-1zM7.5 4a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z">
                    </path>
                    <path d="M6 4.5H1.866a1 1 0 1 0 0 1h2.668A6.517 6.517 0 0 0 1.814 9H2.5c.123 0 .244.015.358.043a5.517 5.517 0 0 1 3.185-3.185A1.503 1.503 0 0 1 6 5.5v-1zm3.957 1.358A1.5 1.5 0 0 0 10 5.5v-1h4.134a1 1 0 1 1 0 1h-2.668a6.517 6.517 0 0 1 2.72 3.5H13.5c-.123 0-.243.015-.358.043a5.517 5.517 0 0 0-3.185-3.185z">
                    </path>
                </svg>
            </span><span>ICode</span>
        </a><button data-bs-toggle="collapse" class="navbar-toggler"
                    data-bs-target="#navcol-1">
            <span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="navbar-nav me-auto">
                <li class="nav-item"><a class="nav-link active" asp-action="Search" asp-controller="Problem">Danh sách bài tập</a></li>
                <li class="nav-item"><a class="nav-link active" asp-action="List" asp-controller="Submission">Danh sách bài nộp</a></li>
                <li class="nav-item"><a class="nav-link" asp-action="CodeExecutor" asp-controller="Home">Live IDE</a></li>
            </ul>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-dark" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        @User.Identity.Name
                        <img class="rounded-circle flex-shrink-0 ms-1 fit-cover border" width="40" height="40" src="@User.FindFirst("Avatar").Value" />
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" asp-action="Index" asp-controller="Profile">Profile</a></li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Home" asp-area="Admin">Quản lí</a></li>
                        }
                        <li><a class="dropdown-item" asp-action="Logout" asp-controller="Auth">Đăng xuất</a></li>
                    </ul>
                </div>
            }
            else
            {
                <div>
                    <a class="btn btn-primary" asp-action="Login" asp-controller="Auth">Đăng nhập</a>
                    <a class="btn btn-primary ms-2" asp-action="Register" asp-controller="Auth">Đăng kí</a>
                </div>
            }
        </div>
    </div>
</nav>

ICode.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link href="~/css/Shared/site.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    @RenderSection("Styles", required: false)
</head>
<body>
    <partial name="_Header" />
    @RenderBody()
    <partial name="_Footer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ICode.Web/Views/Shared/_PlainLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link href="~/css/Shared/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    @RenderSection("Styles", required: false)
</head>
<body>
    @RenderBody()
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ICode.Web/Views/Shared/_ProblemCard.cshtml
@model ProblemDTO
<a class="col text-decoration-none text-dark" asp-action="Index" asp-controller="Problem" asp-route-id="@Model.ID">
    <div class="rounded p-4 bg-white shadow">
        <div class="d-flex justify-content-between align-items-start">
            <div class="d-flex">
                <img class="rounded-circle flex-shrink-0 me-3 fit-cover" width="50" height="50"
                     src="@Model.Author.Avatar">
                <div>
                    <p class="fw-bold mb-0">@Model.Author.Username</p>
                    <p class="text-muted mb-0">@Model.Author.Email</p>
                </div>
            </div>
            <div>
                @foreach (TagDTO tag in Model.Tags)
                {
                    <span class="badge rounded bg-primary mb-2">@tag.Name</span>
                }
            </div>
        </div>
        <div class="d-flex justify-content-between align-items-center mt-2">
            <h4 class="text col-9">@Model.Name</h4>
            <span>@Model.CreatedAt.ToString("dd/MM/yyyy")</span>
        </div>
        <div class="text">
            @Html.Raw(Model.Description)
        </div>
    </div>
</a>